--==========================================================================================================================
-- UnitPromotions
--==========================================================================================================================	
INSERT OR REPLACE INTO UnitPromotions 
			(Type, 											Description, 											Help, 														Sound, 				FriendlyLandsModifier,	IgnoreZOC,	HPHealedIfDestroyEnemy,	LostWithUpgrade,	CannotBeChosen, PortraitIndex,	IconAtlas, 			PediaType, 			PediaEntry,											ShowInPedia)
VALUES		('PROMOTION_JFD_QUINQUEREME_FRIENDLY_LANDS',	'TXT_KEY_PROMOTION_JFD_QUINQUEREME_FRIENDLY_LANDS',		'TXT_KEY_PROMOTION_JFD_QUINQUEREME_FRIENDLY_LANDS_HELP', 	'AS2D_IF_LEVELUP',	20, 					0, 			0, 						1,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_QUINQUEREME_FRIENDLY_LANDS',	1),
			('PROMOTION_JFD_QUINQUEREME_ZOC',				'TXT_KEY_PROMOTION_JFD_QUINQUEREME_ZOC',				'TXT_KEY_PROMOTION_JFD_QUINQUEREME_ZOC_HELP', 				'AS2D_IF_LEVELUP',	0, 						1, 			0, 						0,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_QUINQUEREME_ZOC',			1),
			('PROMOTION_JFD_COTHON',						'TXT_KEY_PROMOTION_JFD_COTHON',							'TXT_KEY_PROMOTION_JFD_COTHON_HELP', 						'AS2D_IF_LEVELUP',	0, 						0, 			0, 						0,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_COTHON',						0),
			('PROMOTION_JFD_HUNDRED_AND_FOUR',				'TXT_KEY_PROMOTION_JFD_HUNDRED_AND_FOUR',				'TXT_KEY_PROMOTION_JFD_HUNDRED_AND_FOUR_HELP', 				'AS2D_IF_LEVELUP',	0, 						0, 			0, 						0,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_HUNDRED_AND_FOUR',			0),
			('PROMOTION_JFD_SHOPHET',						'TXT_KEY_PROMOTION_JFD_SHOPHET',						'TXT_KEY_PROMOTION_JFD_SHOPHET_HELP', 						'AS2D_IF_LEVELUP',	0, 						0, 			0, 						0,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_SHOPHET',					1),
			('PROMOTION_JFD_SHOPHET_ADMIRAL',				'TXT_KEY_PROMOTION_JFD_SHOPHET_ADMIRAL',				'TXT_KEY_PROMOTION_JFD_SHOPHET_ADMIRAL_HELP', 				'AS2D_IF_LEVELUP',	0, 						0, 			0, 						0,					1, 				48, 			'PROMOTION_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_SHOPHET_ADMIRAL',			0),
			('PROMOTION_JFD_SHOPHET_HEAL',					'TXT_KEY_PROMOTION_JFD_SHOPHET_HEAL',					'TXT_KEY_PROMOTION_JFD_SHOPHET_HEAL_HELP',					'AS2D_IF_LEVELUP',	0, 						0, 			25, 					0,					1, 				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_SHOPHET_HEAL',				0),
			('PROMOTION_JFD_SHOPHET_GENERAL',				'TXT_KEY_PROMOTION_JFD_SHOPHET_GENERAL',				'TXT_KEY_PROMOTION_JFD_SHOPHET_GENERAL_HELP', 				'AS2D_IF_LEVELUP',	0, 						0, 			0, 						0,					1, 				48, 			'PROMOTION_ATLAS', 	'PEDIA_ATTRIBUTES', 'TXT_KEY_PROMOTION_JFD_SHOPHET_GENERAL',			1);
--==========================================================================================================================
--==========================================================================================================================