--==========================================================================================================================	
-- MISSIONS
--==========================================================================================================================
-- Missions
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO Missions	
		(Type, 								Time,	OrderPriority,	Sound,	Visible,	Description, 						Help, 										DisabledHelp, 										EntityEventType,				IconAtlas,				IconIndex)
VALUES	('MISSION_FREE_LUXURY', 			20,		199,			0,		1,			'TXT_KEY_MISSION_FREE_LUXURY', 		'TXT_KEY_MISSION_FREE_LUXURY_HELP',			'TXT_KEY_MISSION_FREE_LUXURY_HELP_DISABLED',		'ENTITY_EVENT_GREAT_EVENT',		'UNIT_ACTION_ATLAS',	16),
		('MISSION_RECON_FOUND', 			25,		199,			1,		1,			'TXT_KEY_MISSION_BUILD_CITY', 		'TXT_KEY_MISSION_BUILD_CITY_HELP',			'TXT_KEY_MISSION_BUILD_CITY_DISABLED_HELP',			'ENTITY_EVENT_FOUND',			'UNIT_ACTION_ATLAS',	40);
--==========================================================================================================================
-- UNIT CLASSES
--==========================================================================================================================
-- UnitClasses
--------------------------------------------------------------------------------------------------------------------------	
--Adventurer
INSERT INTO UnitClasses
		(Type, 								DefaultUnit, 					Description)
VALUES	('UNITCLASS_JFD_ADVENTURER',		'UNIT_JFD_ADVENTURER', 			'TXT_KEY_JFD_ADVENTURER');

--Explorer
INSERT INTO UnitClasses
		(Type, 								DefaultUnit, 					Description)
VALUES	('UNITCLASS_JFD_EXPLORER',			'UNIT_JFD_EXPLORER', 			'TXT_KEY_JFD_EXPLORER');
-------------------
-- Civilization_UnitClassOverrides
-------------------
INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType, 			UnitClassType, 						UnitType)
VALUES	('CIVILIZATION_BARBARIAN',	'UNITCLASS_JFD_ADVENTURER', 		null),
		('CIVILIZATION_BARBARIAN',	'UNITCLASS_JFD_EXPLORER', 			null);
--==========================================================================================================================
-- UNITS
--==========================================================================================================================
-- Units
--------------------------------------------------------------------------------------------------------------------------	
--Adventurer
INSERT INTO Units
		(Class, 						Type,					PrereqTech, 				Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, Moves, CombatClass, Domain, DefaultUnitAI, Description, 				Civilopedia, 						Strategy, 							Help, 							NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						UnitFlagAtlas,						UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
SELECT	'UNITCLASS_JFD_ADVENTURER', 	'UNIT_JFD_ADVENTURER', 	'TECH_SCIENTIFIC_THEORY', 	24, 	175, 	350, 		RequiresFaithPurchaseEnabled, 3,	 CombatClass, Domain, DefaultUnitAI, 'TXT_KEY_JFD_ADVENTURER', 	'TXT_KEY_JFD_ADVENTURER_PEDIA', 	'TXT_KEY_JFD_ADVENTURER_STRATEGY', 	'TXT_KEY_JFD_ADVENTURER_HELP', 	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_ADVENTURER',	'JFD_UNIT_FLAG_ADVENTURER_ATLAS',	0, 					'JFD_EXPLORATION_UNIT_ATLAS',	4
FROM Units WHERE Type = 'UNIT_SCOUT';

--Explorer
INSERT INTO Units
		(Class, 						Type,					PrereqTech, 				Combat, Cost, 	FaithCost, 	RequiresFaithPurchaseEnabled, Moves, CombatClass, Domain, DefaultUnitAI, Description, 				Civilopedia, 						Strategy, 							Help, 							ObsoleteTech, 				NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, UnitArtInfo, 						GoodyHutUpgradeUnitClass,	UnitFlagAtlas, 						UnitFlagIconOffset, IconAtlas, 						PortraitIndex)
SELECT	'UNITCLASS_JFD_EXPLORER', 		'UNIT_JFD_EXPLORER', 	'TECH_ASTRONOMY',			16, 	115, 	230, 		RequiresFaithPurchaseEnabled, 3,	 CombatClass, Domain, DefaultUnitAI, 'TXT_KEY_JFD_EXPLORER', 	'TXT_KEY_JFD_EXPLORER_PEDIA',		'TXT_KEY_JFD_EXPLORER_STRATEGY', 	'TXT_KEY_JFD_EXPLORER_HELP', 	'TECH_SCIENTIFIC_THEORY',	NoBadGoodies, Pillage, MilitarySupport, MilitaryProduction, AdvancedStartCost, XPValueAttack, XPValueDefense, 'ART_DEF_UNIT_JFD_EXPLORER', 		'UNITCLASS_JFD_ADVENTURER',	'JFD_UNIT_FLAG_EXPLORER_ATLAS', 	0, 					'JFD_EXPLORATION_UNIT_ATLAS',	2
FROM Units WHERE Type = 'UNIT_SCOUT';

--Scout
UPDATE Units
SET Help = 'TXT_KEY_JFD_SCOUT_HELP', Strategy = 'TXT_KEY_JFD_SCOUT_STRATEGY', IconAtlas = 'JFD_EXPLORATION_UNIT_ATLAS', PortraitIndex = 0
WHERE Type = 'UNIT_SCOUT';

UPDATE Units
SET ObsoleteTech = 'TECH_ASTRONOMY'
WHERE Class = 'UNITCLASS_SCOUT';

CREATE TRIGGER JFDExCE_Scout_Obsolete
AFTER INSERT ON Units 
WHEN NEW.Class = 'UNITCLASS_SCOUT'
BEGIN
	UPDATE Units
	SET ObsoleteTech = 'TECH_ASTRONOMY'
	WHERE Type = NEW.Type;
END;

--Admiral
UPDATE Units
SET Strategy = 'TXT_KEY_UNIT_JFD_GREAT_ADMIRAL_STRATEGY'
WHERE Type = 'UNIT_GREAT_ADMIRAL';
--------------------------------------------------------------------------------------------------------------------------
-- Unit_AITypes
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_JFD_ADVENTURER', 			UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCOUT';

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_JFD_EXPLORER', 			UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCOUT';
--------------------------------------------------------------------------------------------------------------------------	
-- UnitGameplay2DScripts
--------------------------------------------------------------------------------------------------------------------------		
INSERT INTO UnitGameplay2DScripts 	
		(UnitType, 						SelectionSound, FirstSelectionSound)
SELECT	'UNIT_JFD_ADVENTURER', 			SelectionSound, FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT';

INSERT INTO UnitGameplay2DScripts 	
		(UnitType, 						SelectionSound, FirstSelectionSound)
SELECT	'UNIT_JFD_EXPLORER', 			SelectionSound, FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCOUT';
--------------------------------------------------------------------------------------------------------------------------
-- Unit_UniqueNames
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_UniqueNames
		(UnitType, 						UniqueName)
VALUES	('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_1'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_2'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_3'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_4'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_5'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_6'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_7'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_8'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_9'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_10'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_11'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_12'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_13'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_14'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_15'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_16'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_17'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_18'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_19'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_20'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_21'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_22'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_23'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_24'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_25'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_26'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_27'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_28'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_29'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_30'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_31'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_32'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_33'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_34'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_35'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_36'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_37'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_38'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_39'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_40'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_41'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_42'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_43'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_44'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_45'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_46'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_47'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_48'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_49'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_50'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_51'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_52'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_53'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_54'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_55'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_56'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_57'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_58'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_59'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_60'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_61'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_62'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_63'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_64'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_65'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_66'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_67'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_68'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_69'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_70'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_71'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_72'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_73'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_74'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_75'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_76'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_77'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_78'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_79'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_80'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_81'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_82'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_83'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_84'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_85'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_86'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_87'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_88'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_89'),
		('UNIT_SCOUT', 					'TXT_KEY_GREAT_PERSON_JFD_GREAT_RECON_90');
			
DELETE FROM Unit_UniqueNames WHERE UnitType IN ('UNIT_GREAT_ADMIRAL', 'UNIT_GREAT_GENERAL', 'UNIT_MERCHANT');			
INSERT INTO Unit_UniqueNames
		(UnitType, 						UniqueName)
VALUES	('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_1'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_2'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_3'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_4'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_5'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_6'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_7'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_8'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_9'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_10'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_11'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_12'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_13'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_14'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_15'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_16'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_17'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_18'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_19'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_20'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_21'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_22'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_23'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_24'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_25'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_26'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_27'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_28'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_29'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_30'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_31'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_32'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_33'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_34'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_35'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_36'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_37'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_38'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_39'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_40'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_41'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_42'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_43'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_44'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_45'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_46'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_47'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_48'),
		('UNIT_GREAT_ADMIRAL', 			'TXT_KEY_GREAT_PERSON_JFD_GREAT_ADMIRAL_49'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_1'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_2'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_3'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_4'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_5'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_6'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_7'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_8'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_9'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_10'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_11'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_12'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_13'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_14'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_15'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_16'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_17'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_18'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_19'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_20'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_21'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_22'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_23'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_24'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_25'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_26'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_27'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_28'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_29'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_30'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_31'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_32'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_33'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_34'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_35'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_36'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_37'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_38'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_39'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_40'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_41'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_42'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_43'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_44'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_45'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_46'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_47'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_48'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_49'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_50'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_51'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_52'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_53'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_54'),
        ('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_55'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_56'),
		('UNIT_GREAT_GENERAL',  		'TXT_KEY_GREAT_PERSON_JFD_GREAT_GENERAL_57'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_1'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_2'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_3'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_4'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_5'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_6'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_7'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_8'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_9'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_10'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_11'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_12'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_13'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_14'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_15'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_16'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_17'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_18'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_19'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_20'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_21'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_22'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_23'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_24'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_25'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_26'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_27'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_28'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_29'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_30'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_31'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_32'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_33'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_34'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_35'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_36'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_37'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_38'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_39'),
        ('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_40'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_41'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_42'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_43'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_44'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_45'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_46'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_47'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_48'),
		('UNIT_MERCHANT',  				'TXT_KEY_GREAT_PERSON_JFD_GREAT_MERCHANT_49');

INSERT INTO Unit_UniqueNames
		(UnitType,						UniqueName)
SELECT	'UNIT_JFD_ADVENTURER',			UniqueName
FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT';

INSERT INTO Unit_UniqueNames
		(UnitType,						UniqueName)
SELECT	'UNIT_JFD_EXPLORER',			UniqueName
FROM Unit_UniqueNames WHERE UnitType = 'UNIT_SCOUT';
--------------------------------------------------------------------------------------------------------------------------
-- Unit_Flavors
-----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_Flavors
		(UnitType,						FlavorType, Flavor)
SELECT	'UNIT_JFD_ADVENTURER', 			FlavorType, 20
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT';

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType, Flavor)
SELECT	'UNIT_JFD_EXPLORER', 			FlavorType, 15
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCOUT';
--------------------------------------------------------------------------------------------------------------------------
-- Unit_ClassUpgrades
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_ClassUpgrades
		(UnitType,					UnitClassType)
VALUES	('UNIT_JFD_EXPLORER', 		'UNITCLASS_JFD_ADVENTURER');

INSERT INTO Unit_ClassUpgrades
		(UnitType,		UnitClassType)
SELECT	Type, 			'UNITCLASS_JFD_EXPLORER'
FROM Units WHERE Class = 'UNITCLASS_SCOUT';

CREATE TRIGGER JFDExCE_Unit_ClassUpgradesScout
AFTER INSERT ON Units 
WHEN NEW.Class = 'UNITCLASS_SCOUT'
BEGIN
	INSERT INTO Unit_ClassUpgrades
			(UnitType, 				UnitClassType)
	VALUES	(NEW.Type,				'UNITCLASS_JFD_EXPLORER');
END;
--------------------------------------------------------------------------------------------------------------------------
-- Unit_FreePromotions
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_FreePromotions
		(UnitType,			PromotionType)
SELECT	Type, 				'PROMOTION_JFD_GREAT_RECON'
FROM Units WHERE Class = 'UNITCLASS_SCOUT';

CREATE TRIGGER JFDExCE_Unit_FreePromotionsScout
AFTER INSERT ON Units 
WHEN NEW.Class = 'UNITCLASS_SCOUT'
BEGIN
	INSERT INTO Unit_FreePromotions
			(UnitType, 		PromotionType)
	VALUES	(NEW.Type,		'PROMOTION_JFD_GREAT_RECON');
END;
	
INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JFD_ADVENTURER', 		Type
FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_EXTRA_SIGHT_I', 'PROMOTION_FOREIGN_LANDS');

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JFD_EXPLORER', 		Type
FROM UnitPromotions WHERE Type IN ('PROMOTION_JFD_GREAT_RECON', 'PROMOTION_IGNORE_TERRAIN_COST', 'PROMOTION_EXTRA_SIGHT_I');
--==========================================================================================================================
--==========================================================================================================================