ALTER TABLE Policies
	ADD Dummy INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('BUGFIX_DUMMY_POLICIES', 1);

ALTER TABLE Buildings
	ADD ShowInPedia INTEGER DEFAULT 1;
ALTER TABLE Improvements
	ADD ShowInPedia INTEGER DEFAULT 1;
ALTER TABLE Technologies
	ADD ShowInPedia INTEGER DEFAULT 1;
ALTER TABLE UnitPromotions
	ADD ShowInPedia INTEGER DEFAULT 1;
ALTER TABLE Resources
	ADD ShowInPedia INTEGER DEFAULT 1;
ALTER TABLE Features
	ADD ShowInPedia INTEGER DEFAULT 1;