--==========================================================================================================================
-- Unit_UniqueNames
--==========================================================================================================================
INSERT INTO Unit_UniqueNames 
			(UnitType, 						UniqueName,										GreatWorkType)
VALUES		('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_1',		'GREAT_WORK_BIRTH_OF_WAINAMOINEN'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_2',		'GREAT_WORK_WAINAMOINENS_SOWING'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_3',		'GREAT_WORK_JOUKAHAINEN'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_4',		'GREAT_WORK_AINO_AND_THE_WATER-MAIDENS'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_5',		'GREAT_WORK_ORIGIN_OF_IRON'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_6',		'GREAT_WORK_ILMARINEN'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_7',		'GREAT_WORK_ILMARINEN_FORGES_THE_SAMPO'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_8',		'GREAT_WORK_LEMMINKAINENS_RESTORATION'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_9',		'GREAT_WORK_WAINAMOINENS_BOAT-BUILDING'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_10',		'GREAT_WORK_THE_BREWING_OF_BEER'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_11',		'GREAT_WORK_WAINAMOINENS_HARP'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_12',		'GREAT_WORK_LOUHI_SUMMONS_THE_SEA-MONSTER'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_13',		'GREAT_WORK_FRAGMENTING_OF_THE_SAMPO'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_14',		'GREAT_WORK_LOUHI_STEALS_SUN_MOON_AND_FIRE'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_15',		'GREAT_WORK_KULLERVOS_EVIL_DEEDS'),
			('UNIT_FINNIC_RUNE_SINGER', 	'TXT_KEY_GREAT_PERSON_RUNE_SINGER_DESC_16',		'GREAT_WORK_WAINAMOINENS_DEPARTURE');
--==========================================================================================================================
--==========================================================================================================================		
		
			