-- Give all recon units PROMOTION_XP_FOR_SCOUTING
INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
SELECT Type, 'PROMOTION_XP_FOR_SCOUTING' FROM Units WHERE Class IN ('UNITCLASS_SCOUT', 'UNITCLASS_JFD_ADVENTURER', 'UNITCLASS_JFD_EXPLORER');
	
-- Update any additional recon units to have PROMOTION_XP_FOR_SCOUTING as well
CREATE TRIGGER FreeXpForScouting
AFTER INSERT ON Units
WHEN NEW.Class IN ('UNITCLASS_SCOUT', 'UNITCLASS_JFD_ADVENTURER', 'UNITCLASS_JFD_EXPLORER')
BEGIN
	INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
	VALUES(NEW.Type, 'PROMOTION_XP_FOR_SCOUTING');
END;