--==========================================================================================================================	
-- UnitPromotions
--==========================================================================================================================
UPDATE UnitPromotions
SET PromotionPrereqOr4 = 'PROMOTION_SHELLING_1', PediaType = 'PEDIA_SHARED'
WHERE Type = 'PROMOTION_SENTRY';

UPDATE UnitPromotions
SET PromotionPrereqOr3 = null, PromotionPrereqOr4 = null
WHERE Type = 'PROMOTION_SIEGE';

UPDATE UnitPromotions
SET PromotionPrereqOr3 = 'PROMOTION_SCOUTING_1', PromotionPrereqOr4 = 'PROMOTION_SURVIVALISM_1'
WHERE Type = 'PROMOTION_MEDIC';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_MELEE'
WHERE Type = 'PROMOTION_AMPHIBIOUS';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = null, PromotionPrereqOr2 = null, PromotionPrereqOr3 = null, PromotionPrereqOr4 = null, PediaType = 'PEDIA_ATTRIBUTES'
WHERE Type = 'PROMOTION_INDIRECT_FIRE';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_1', PromotionPrereqOr2 = 'PROMOTION_DRILL_1', PromotionPrereqOr3 = null, PromotionPrereqOr4 = null
WHERE Type = 'PROMOTION_FORMATION_1';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_1', PromotionPrereqOr2 = 'PROMOTION_DRILL_1'
WHERE Type = 'PROMOTION_AMBUSH_1';

UPDATE UnitPromotions
SET PromotionPrereqOr2 = 'PROMOTION_SHELLING_2'
WHERE Type = 'PROMOTION_SUPPLY';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_2', PromotionPrereqOr2 = 'PROMOTION_DRILL_2'
WHERE Type = 'PROMOTION_MARCH';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_2', PromotionPrereqOr2 = 'PROMOTION_DRILL_2'
WHERE Type = 'PROMOTION_WOODSMAN';

UPDATE UnitPromotions
SET PromotionPrereqOr4 = 'PROMOTION_SHELLING_3', PromotionPrereqOr8 = 'PROMOTION_ARMOR_PLATING_3', PediaType = 'PEDIA_SHARED'
WHERE Type = 'PROMOTION_LOGISTICS';

UPDATE UnitPromotions
SET PromotionPrereqOr4 = 'PROMOTION_SHELLING_2'
WHERE Type = 'PROMOTION_RANGE';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_1', PromotionPrereqOr2 = 'PROMOTION_DRILL_1', PromotionPrereqOr4 = 'PROMOTION_SHELLING_1', PediaType = 'PEDIA_SHARED'
WHERE Type = 'PROMOTION_MOBILITY';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_AIR'
WHERE Type = 'PROMOTION_BOMBARDMENT_1';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_AIR'
WHERE Type = 'PROMOTION_BOMBARDMENT_2';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_AIR'
WHERE Type = 'PROMOTION_BOMBARDMENT_3';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_SHOCK_2', PromotionPrereqOr2 = 'PROMOTION_DRILL_2'
WHERE Type = 'PROMOTION_REPAIR';

UPDATE UnitPromotions
SET PromotionPrereqOr3 = 'PROMOTION_HELI_MOBILITY_3', PromotionPrereqOr4 = 'PROMOTION_HELI_AMBUSH_2', PromotionPrereqOr5 = 'PROMOTION_HELI_TARGETING_2', Description = 'TXT_KEY_PROMOTION_F0S_AIR_LOGISTICS', PediaEntry = 'TXT_KEY_PROMOTION_F0S_AIR_LOGISTICS_PEDIA'
WHERE Type = 'PROMOTION_AIR_LOGISTICS';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_SCOUTING'
WHERE Type = 'PROMOTION_SURVIVALISM_1';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_SCOUTING'
WHERE Type = 'PROMOTION_SURVIVALISM_2';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_SCOUTING'
WHERE Type = 'PROMOTION_SURVIVALISM_3';

UPDATE UnitPromotions
SET PromotionPrereqOr1 = 'PROMOTION_HELI_MOBILITY_2', PromotionPrereqOr2 = 'PROMOTION_HELI_AMBUSH_1', PromotionPrereqOr3 = 'PROMOTION_HELI_TARGETING_1', PediaType = 'PEDIA_HEAL', Description = 'TXT_KEY_PROMOTION_F0S_HELI_REPAIR', Help = 'TXT_KEY_PROMOTION_F0S_HELI_REPAIR_HELP', PediaEntry = 'TXT_KEY_PROMOTION_F0S_HELI_REPAIR_PEDIA'
WHERE Type = 'PROMOTION_HELI_REPAIR';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_WOLFPACK_1';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_WOLFPACK_2';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_WOLFPACK_3';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_FLIGHT_DECK_1';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_FLIGHT_DECK_2';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_FLIGHT_DECK_3';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_ARMOR_PLATING_1';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_ARMOR_PLATING_2';

UPDATE UnitPromotions
SET PediaType = 'PEDIA_NAVAL'
WHERE Type = 'PROMOTION_ARMOR_PLATING_3';

UPDATE UnitPromotions
SET SameTileHealChange = 20
WHERE Type = 'PROMOTION_MEDIC_GENERAL';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_AIR', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_AIR', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_AIR'
WHERE Type = 'PROMOTION_ANTI_AIR';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_PARTIAL_HEAL_IF_DESTROY_ENEMY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_PARTIAL_HEAL_IF_DESTROY_ENEMY'
WHERE Type = 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_HELICOPTER', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_HELICOPTER', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_HELICOPTER'
WHERE Type = 'PROMOTION_ANTI_HELICOPTER';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_NAVAL_BONUS', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_NAVAL_BONUS', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_NAVAL_BONUS'
WHERE Type = 'PROMOTION_NAVAL_BONUS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_SUBMARINE_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_SUBMARINE_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_SUBMARINE_I'
WHERE Type = 'PROMOTION_ANTI_SUBMARINE_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_SUBMARINE_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_SUBMARINE_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_SUBMARINE_II'
WHERE Type = 'PROMOTION_ANTI_SUBMARINE_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FLAT_MOVEMENT_COST'
WHERE Type = 'PROMOTION_FLAT_MOVEMENT_COST';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_TANK', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_TANK', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_TANK'
WHERE Type = 'PROMOTION_ANTI_TANK';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SILENT_HUNTER'
WHERE Type = 'PROMOTION_SILENT_HUNTER';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CARGO_I'
WHERE Type = 'PROMOTION_CARGO_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CARGO_II'
WHERE Type = 'PROMOTION_CARGO_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CARGO_III'
WHERE Type = 'PROMOTION_CARGO_III';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CARGO_IV'
WHERE Type = 'PROMOTION_CARGO_IV';

UPDATE UnitPromotions
SET FriendlyLandsAttackModifier = 25
WHERE Type = 'PROMOTION_NATIONALISM';

UPDATE UnitPromotions
SET OpenAttack = 25, RoughAttack = 25
WHERE Type = 'PROMOTION_LIGHTNING_WARFARE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CITY_SIEGE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_CITY_SIEGE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_CITY_SIEGE'
WHERE Type = 'PROMOTION_CITY_SIEGE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CITY_ASSAULT', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_CITY_ASSAULT', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_CITY_ASSAULT'
WHERE Type = 'PROMOTION_CITY_ASSAULT';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_NO_DEFENSIVE_BONUSES', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_NO_DEFENSIVE_BONUSES', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_NO_DEFENSIVE_BONUSES'
WHERE Type = 'PROMOTION_NO_DEFENSIVE_BONUSES';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_MUST_SET_UP', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_MUST_SET_UP', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_MUST_SET_UP'
WHERE Type = 'PROMOTION_MUST_SET_UP';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SIGHT_PENALTY'
WHERE Type = 'PROMOTION_SIGHT_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ONLY_DEFENSIVE'
WHERE Type = 'PROMOTION_ONLY_DEFENSIVE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_MOUNTED_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_MOUNTED_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_MOUNTED_I'
WHERE Type = 'PROMOTION_ANTI_MOUNTED_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_MOUNTED_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_MOUNTED_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_MOUNTED_II'
WHERE Type = 'PROMOTION_ANTI_MOUNTED_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FREE_PILLAGE_MOVES', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_FREE_PILLAGE_MOVES', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_FREE_PILLAGE_MOVES'
WHERE Type = 'PROMOTION_FREE_PILLAGE_MOVES';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FOREIGN_LANDS'
WHERE Type = 'PROMOTION_FOREIGN_LANDS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_AIR_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_AIR_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_AIR_II'
WHERE Type = 'PROMOTION_ANTI_AIR_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_INTERCEPTION_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_INTERCEPTION_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_INTERCEPTION_I'
WHERE Type = 'PROMOTION_INTERCEPTION_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_INTERCEPTION_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_INTERCEPTION_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_INTERCEPTION_II'
WHERE Type = 'PROMOTION_INTERCEPTION_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_INTERCEPTION_III', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_INTERCEPTION_III', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_INTERCEPTION_III'
WHERE Type = 'PROMOTION_INTERCEPTION_III';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_INTERCEPTION_IV', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_INTERCEPTION_IV', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_INTERCEPTION_IV'
WHERE Type = 'PROMOTION_INTERCEPTION_IV';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_WITHDRAW_BEFORE_MELEE'
WHERE Type = 'PROMOTION_WITHDRAW_BEFORE_MELEE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_OCEAN_IMPASSABLE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_OCEAN_IMPASSABLE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_OCEAN_IMPASSABLE'
WHERE Type = 'PROMOTION_OCEAN_IMPASSABLE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CITY_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_CITY_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_CITY_PENALTY'
WHERE Type = 'PROMOTION_CITY_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_CAN_MOVE_AFTER_ATTACKING'
WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FEARED_ELEPHANT'
WHERE Type = 'PROMOTION_FEARED_ELEPHANT';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_PRIZE_SHIPS', LostWithUpgrade = 1
WHERE Type = 'PROMOTION_PRIZE_SHIPS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_STEAM_POWERED', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_STEAM_POWERED', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_STEAM_POWERED'
WHERE Type = 'PROMOTION_STEAM_POWERED';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FIRE_SUPPORT', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_FIRE_SUPPORT', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_FIRE_SUPPORT'
WHERE Type = 'PROMOTION_FIRE_SUPPORT';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EXTRA_SIGHT_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EXTRA_SIGHT_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EXTRA_SIGHT_I'
WHERE Type = 'PROMOTION_EXTRA_SIGHT_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EXTRA_SIGHT_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EXTRA_SIGHT_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EXTRA_SIGHT_II'
WHERE Type = 'PROMOTION_EXTRA_SIGHT_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EXTRA_SIGHT_III', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EXTRA_SIGHT_III', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EXTRA_SIGHT_III'
WHERE Type = 'PROMOTION_EXTRA_SIGHT_III';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EXTRA_SIGHT_IV', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EXTRA_SIGHT_IV', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EXTRA_SIGHT_IV'
WHERE Type = 'PROMOTION_EXTRA_SIGHT_IV';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_IGNORE_TERRAIN_COST', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_IGNORE_TERRAIN_COST', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_IGNORE_TERRAIN_COST'
WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_GOLDEN_AGE_POINTS', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_GOLDEN_AGE_POINTS', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_GOLDEN_AGE_POINTS'
WHERE Type = 'PROMOTION_GOLDEN_AGE_POINTS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HEAVY_PAYLOAD', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_HEAVY_PAYLOAD', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_HEAVY_PAYLOAD'
WHERE Type = 'PROMOTION_HEAVY_PAYLOAD';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_GREAT_GENERAL', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_GREAT_GENERAL', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_GREAT_GENERAL'
WHERE Type = 'PROMOTION_GREAT_GENERAL';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HAKA_WAR_DANCE'
WHERE Type = 'PROMOTION_HAKA_WAR_DANCE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FLANK_ATTACK_BONUS', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_FLANK_ATTACK_BONUS', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_FLANK_ATTACK_BONUS'
WHERE Type = 'PROMOTION_FLANK_ATTACK_BONUS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SECOND_ATTACK', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_SECOND_ATTACK', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_SECOND_ATTACK'
WHERE Type = 'PROMOTION_SECOND_ATTACK';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ANTI_FIGHTER', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ANTI_FIGHTER', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ANTI_FIGHTER'
WHERE Type = 'PROMOTION_ANTI_FIGHTER';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_RIVAL_TERRITORY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_RIVAL_TERRITORY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_RIVAL_TERRITORY'
WHERE Type = 'PROMOTION_RIVAL_TERRITORY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HEAVY_CHARGE'
WHERE Type = 'PROMOTION_HEAVY_CHARGE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_DEFEND_NEAR_CAPITAL'
WHERE Type = 'PROMOTION_DEFEND_NEAR_CAPITAL';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HEAL_IF_DESTROY_ENEMY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_HEAL_IF_DESTROY_ENEMY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_HEAL_IF_DESTROY_ENEMY'
WHERE Type = 'PROMOTION_HEAL_IF_DESTROY_ENEMY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ATTACK_BONUS', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ATTACK_BONUS', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ATTACK_BONUS'
WHERE Type = 'PROMOTION_ATTACK_BONUS';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ROUGH_TERRAIN_ENDS_TURN'
WHERE Type = 'PROMOTION_ROUGH_TERRAIN_ENDS_TURN';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SPAWN_GENERALS_I'
WHERE Type = 'PROMOTION_SPAWN_GENERALS_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SPAWN_GENERALS_II'
WHERE Type = 'PROMOTION_SPAWN_GENERALS_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_DEFENSE_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_DEFENSE_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_DEFENSE_PENALTY'
WHERE Type = 'PROMOTION_DEFENSE_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FASTER_HEAL', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_FASTER_HEAL', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_FASTER_HEAL'
WHERE Type = 'PROMOTION_FASTER_HEAL';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_STRONGER_DAMAGED', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_STRONGER_DAMAGED', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_STRONGER_DAMAGED'
WHERE Type = 'PROMOTION_STRONGER_VS_DAMAGED';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SMALL_CITY_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_SMALL_CITY_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_SMALL_CITY_PENALTY'
WHERE Type = 'PROMOTION_SMALL_CITY_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HELI_AMBUSH_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_HELI_AMBUSH_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_HELI_AMBUSH_I', PediaType = 'PEDIA_AIR', PromotionPrereqOr1 = 'PROMOTION_HELI_MOBILITY_1'
WHERE Type = 'PROMOTION_HELI_AMBUSH_1';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_HELI_AMBUSH_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_HELI_AMBUSH_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_HELI_AMBUSH_II', PediaType = 'PEDIA_AIR'
WHERE Type = 'PROMOTION_HELI_AMBUSH_2';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_FOLIAGE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_FOLIAGE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_FOLIAGE'
WHERE Type = 'PROMOTION_FOLIAGE_IMPASSABLE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SEE_SUB', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_SEE_SUB', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_SEE_SUB'
WHERE Type = 'PROMOTION_SEE_INVISIBLE_SUBMARINE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_OPEN_TERRAIN', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_OPEN_TERRAIN', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_OPEN_TERRAIN'
WHERE Type = 'PROMOTION_OPEN_TERRAIN';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EVASION_I', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EVASION_I', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EVASION_I'
WHERE Type = 'PROMOTION_EVASION_I';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EVASION_II', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EVASION_II', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EVASION_II'
WHERE Type = 'PROMOTION_EVASION_II';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_INVISIBLE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_INVISIBLE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_INVISIBLE'
WHERE Type = 'PROMOTION_INVISIBLE_SUBMARINE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_ENTER_ICE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_ENTER_ICE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_ENTER_ICE'
WHERE Type = 'PROMOTION_CAN_MOVE_IMPASSABLE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_MAY_PARADROP', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_MAY_PARADROP', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_MAY_PARADROP'
WHERE Type = 'PROMOTION_PARADROP';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_NAVAL_MOVEMENT', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_NAVAL_MOVEMENT', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_NAVAL_MOVEMENT'
WHERE Type = 'PROMOTION_OCEAN_MOVEMENT';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_MOUNTED_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_MOUNTED_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_MOUNTED_PENALTY'
WHERE Type = 'PROMOTION_MOUNTED_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_NAVAL_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_NAVAL_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_NAVAL_PENALTY'
WHERE Type = 'PROMOTION_NAVAL_PENALTY';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_RANGED_SUPPORT', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_RANGED_SUPPORT', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_RANGED_SUPPORT'
WHERE Type = 'PROMOTION_RANGED_SUPPORT_FIRE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_SKYRANGER', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_SKYRANGER', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_SKYRANGER'
WHERE Type = 'PROMOTION_EXTENDED_PARADROP';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_NO_CAPTURE', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_NO_CAPTURE', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_NO_CAPTURE'
WHERE Type = 'PROMOTION_NO_CAPTURE';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_EVANGELIST', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_EVANGELIST', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_EVANGELIST'
WHERE Type = 'PROMOTION_UNWELCOME_EVANGELIST';

UPDATE UnitPromotions
SET Help = 'TXT_KEY_F0S_PROMOTION_HELP_RANGED_PENALTY', Description = 'TXT_KEY_F0S_PROMOTION_DESCRIPTION_RANGED_PENALTY', PediaEntry = 'TXT_KEY_F0S_PROMOTION_PEDIA_ENTRY_RANGED_PENALTY'
WHERE Type = 'PROMOTION_WEAK_RANGED';

UPDATE UnitPromotions
SET RangedDefenseMod = 25, PediaType = 'PEDIA_SHARED'
WHERE Type = 'PROMOTION_COVER_1';

UPDATE UnitPromotions
SET RangedDefenseMod = 25, PediaType = 'PEDIA_SHARED'
WHERE Type = 'PROMOTION_COVER_2';

UPDATE UnitPromotions
SET VisibilityChange = 1
WHERE Type = 'PROMOTION_SCOUTING_3';

INSERT INTO UnitPromotions 						
		(Type, 									Description, 										Help, 													Sound, 				PromotionPrereqOr1,				CannotBeChosen, LostWithUpgrade,	AttackMod,	DefenseMod,		CityAttack,	MovesChange,	RangeChange,	OrderPriority,	PortraitIndex, 	IconAtlas, 			PediaType, 				PediaEntry,											ShowInPedia)
VALUES	('PROMOTION_CITY_SIEGE_WEAK',			'TXT_KEY_PROMOTION_F0S_CITY_SIEGE_WEAK',			'TXT_KEY_PROMOTION_F0S_CITY_SIEGE_WEAK_HELP',			'AS2D_IF_LEVELUP', 	null,							1, 				1,					0,			0,				100,		0,				0,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_CITY_SIEGE_WEAK_PEDIA',		1),
		('PROMOTION_ANTI_TANK_WEAK',			'TXT_KEY_PROMOTION_F0S_ANTI_TANK_WEAK',				'TXT_KEY_PROMOTION_F0S_ANTI_TANK_WEAK_HELP',			'AS2D_IF_LEVELUP', 	null,							1, 				1,					0,			0,				0,			0,				0,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_ANTI_TANK_WEAK_PEDIA',		1),
		('PROMOTION_SHELLING_1',				'TXT_KEY_PROMOTION_F0S_SHELLING_1',					'TXT_KEY_PROMOTION_F0S_SHELLING_1_HELP',				'AS2D_IF_LEVELUP', 	null,							0, 				0,					0,			0,				0,			0,				0,				2,				10, 			'PROMOTION_ATLAS', 	'PEDIA_NAVAL', 			'TXT_KEY_PROMOTION_F0S_SHELLING_1_PEDIA',			1),
		('PROMOTION_SHELLING_2',				'TXT_KEY_PROMOTION_F0S_SHELLING_2',					'TXT_KEY_PROMOTION_F0S_SHELLING_2_HELP',				'AS2D_IF_LEVELUP', 	'PROMOTION_SHELLING_1',			0, 				0,					0,			0,				0,			0,				0,				2,				11, 			'PROMOTION_ATLAS', 	'PEDIA_NAVAL', 			'TXT_KEY_PROMOTION_F0S_SHELLING_2_PEDIA',			1),
		('PROMOTION_SHELLING_3',				'TXT_KEY_PROMOTION_F0S_SHELLING_3',					'TXT_KEY_PROMOTION_F0S_SHELLING_3_HELP',				'AS2D_IF_LEVELUP', 	'PROMOTION_SHELLING_2',			0, 				0,					0,			0,				0,			0,				0,				2,				12, 			'PROMOTION_ATLAS', 	'PEDIA_NAVAL', 			'TXT_KEY_PROMOTION_F0S_SHELLING_3_PEDIA',			1),
		('PROMOTION_HELI_MOBILITY_3',			'TXT_KEY_PROMOTION_F0S_HELI_MOBILITY_3',			'TXT_KEY_PROMOTION_MOBILITY_HELP',					'AS2D_IF_LEVELUP', 	'PROMOTION_HELI_MOBILITY_2',	0, 				0,					0,			0,				0,			1,				0,				2,				33, 			'PROMOTION_ATLAS', 	'PEDIA_AIR', 			'TXT_KEY_PROMOTION_F0S_HELI_MOBILITY_3_PEDIA',		1),
		('PROMOTION_HELI_TARGETING_1',			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_1',			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_1_HELP',			'AS2D_IF_LEVELUP', 	'PROMOTION_HELI_MOBILITY_1',	0, 				0,					0,			0,				0,			0,				0,				3,				52, 			'PROMOTION_ATLAS', 	'PEDIA_AIR', 			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_1_PEDIA',		1),
		('PROMOTION_HELI_TARGETING_2',			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_2',			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_2_HELP',			'AS2D_IF_LEVELUP', 	'PROMOTION_HELI_TARGETING_1',	0, 				0,					0,			0,				0,			0,				0,				3,				53, 			'PROMOTION_ATLAS', 	'PEDIA_AIR', 			'TXT_KEY_PROMOTION_F0S_HELI_TARGETING_2_PEDIA',		1),
		('PROMOTION_BATTERY_INFO',				'TXT_KEY_PROMOTION_F0S_BATTERY_INFO',				'TXT_KEY_PROMOTION_F0S_BATTERY_INFO_HELP',				'AS2D_IF_LEVELUP', 	null,							1, 				1,					0,			0,				0,			0,				0,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_BATTERY_INFO',				1),
		('PROMOTION_BATTERY',					'TXT_KEY_PROMOTION_F0S_BATTERY',					'TXT_KEY_PROMOTION_F0S_BATTERY_HELP',					'AS2D_IF_LEVELUP', 	null,							1, 				1,					0,			0,				0,			0,				1,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_BATTERY',					0),
		('PROMOTION_STRENGTH_FROM_FAITH_INFO', 	'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH_INFO',	'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH_INFO_HELP', 	'AS2D_IF_LEVELUP', 	null,							1, 				0, 					0,			0,				0,			0,				0,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH_INFO',	1),
		('PROMOTION_STRENGTH_FROM_FAITH', 		'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH',		'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH_HELP', 		'AS2D_IF_LEVELUP', 	null,							1, 				0, 					25,			25,				0,			0,				0,				0,				59, 			'ABILITY_ATLAS', 	'PEDIA_ATTRIBUTES', 	'TXT_KEY_PROMOTION_F0S_STRENGTH_FROM_FAITH',		0);
--==========================================================================================================================	
-- UnitPromotions_UnitCombatMods
--==========================================================================================================================
DELETE FROM UnitPromotions_UnitCombatMods WHERE PromotionType = 'PROMOTION_ANTI_AIR';

UPDATE UnitPromotions_UnitCombatMods
SET Modifier = 50
WHERE PromotionType = 'PROMOTION_AIR_AMBUSH_1';

UPDATE UnitPromotions_UnitCombatMods
SET Modifier = 50
WHERE PromotionType = 'PROMOTION_AIR_AMBUSH_2';

UPDATE UnitPromotions_UnitCombatMods
SET Modifier = 33
WHERE PromotionType = 'PROMOTION_HELI_AMBUSH_1';

UPDATE UnitPromotions_UnitCombatMods
SET Modifier = 33
WHERE PromotionType = 'PROMOTION_HELI_AMBUSH_2';

INSERT INTO UnitPromotions_UnitCombatMods 	
			(PromotionType, 				UnitCombatType,					Modifier)
VALUES		('PROMOTION_ANTI_TANK_WEAK', 	'UNITCOMBAT_ARMOR',				50),
			('PROMOTION_ANTI_AIR', 			'UNITCOMBAT_HELICOPTER',		100),
			('PROMOTION_FORMATION_1', 		'UNITCOMBAT_MOUNTED_RANGED',	33),
			('PROMOTION_FORMATION_2', 		'UNITCOMBAT_MOUNTED_RANGED',	33),
			('PROMOTION_ANTI_MOUNTED_I', 	'UNITCOMBAT_MOUNTED_RANGED',	50),
			('PROMOTION_ANTI_MOUNTED_II', 	'UNITCOMBAT_MOUNTED_RANGED',	100),
			('PROMOTION_MOUNTED_PENALTY', 	'UNITCOMBAT_MOUNTED_RANGED',	-33),
			('PROMOTION_NAVAL_BONUS', 		'UNITCOMBAT_SUBMARINE',			50),
			('PROMOTION_NAVAL_BONUS', 		'UNITCOMBAT_CARRIER',			50);
--==========================================================================================================================	
-- UnitPromotions_Features
--==========================================================================================================================
DELETE FROM UnitPromotions_Features WHERE PromotionType = 'PROMOTION_JAGUAR' AND FeatureType = 'FEATURE_FOREST';
--==========================================================================================================================	
-- UnitPromotions_Domains
--==========================================================================================================================
UPDATE UnitPromotions_Domains
SET Modifier = 50
WHERE PromotionType = 'PROMOTION_AIR_TARGETING_1';

UPDATE UnitPromotions_Domains
SET Modifier = 50
WHERE PromotionType = 'PROMOTION_AIR_TARGETING_2';

INSERT INTO UnitPromotions_Domains 	
			(PromotionType, 				DomainType,		Modifier)
VALUES		('PROMOTION_SHELLING_1', 		'DOMAIN_LAND',	15),
			('PROMOTION_SHELLING_2', 		'DOMAIN_LAND',	15),
			('PROMOTION_SHELLING_3', 		'DOMAIN_LAND',	15),
			('PROMOTION_HELI_TARGETING_1', 	'DOMAIN_SEA',	33),
			('PROMOTION_HELI_TARGETING_2', 	'DOMAIN_SEA',	33),
			('PROMOTION_ANTI_AIR', 			'DOMAIN_AIR',	100);
--==========================================================================================================================	
-- UnitPromotions_UnitCombats
--==========================================================================================================================
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_BOMBARDMENT_1' AND UnitCombatType = 'UNITCOMBAT_NAVALRANGED';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_BOMBARDMENT_2' AND UnitCombatType = 'UNITCOMBAT_NAVALRANGED';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_BOMBARDMENT_3' AND UnitCombatType = 'UNITCOMBAT_NAVALRANGED';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_TARGETING_1' AND UnitCombatType = 'UNITCOMBAT_SUBMARINE';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_TARGETING_2' AND UnitCombatType = 'UNITCOMBAT_SUBMARINE';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_TARGETING_3' AND UnitCombatType = 'UNITCOMBAT_SUBMARINE';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_FORMATION_1' AND UnitCombatType = 'UNITCOMBAT_MELEE';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_AMBUSH_1' AND UnitCombatType = 'UNITCOMBAT_MELEE';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_FORMATION_1' AND UnitCombatType = 'UNITCOMBAT_GUN';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_AMBUSH_1' AND UnitCombatType = 'UNITCOMBAT_GUN';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_FORMATION_1' AND UnitCombatType = 'UNITCOMBAT_ARMOR';
DELETE FROM UnitPromotions_UnitCombats WHERE PromotionType = 'PROMOTION_MARCH' AND UnitCombatType = 'UNITCOMBAT_SIEGE';

INSERT INTO UnitPromotions_UnitCombats 	
			(PromotionType, 				UnitCombatType)
VALUES		('PROMOTION_SHELLING_1', 		'UNITCOMBAT_NAVALRANGED'),
			('PROMOTION_SHELLING_2', 		'UNITCOMBAT_NAVALRANGED'),
			('PROMOTION_SHELLING_3', 		'UNITCOMBAT_NAVALRANGED'),
			('PROMOTION_ARMOR_PLATING_1', 	'UNITCOMBAT_SUBMARINE'),
			('PROMOTION_ARMOR_PLATING_2', 	'UNITCOMBAT_SUBMARINE'),
			('PROMOTION_ARMOR_PLATING_3', 	'UNITCOMBAT_SUBMARINE'),
			('PROMOTION_HELI_MOBILITY_3', 	'UNITCOMBAT_HELICOPTER'),
			('PROMOTION_HELI_TARGETING_1', 	'UNITCOMBAT_HELICOPTER'),
			('PROMOTION_HELI_TARGETING_2', 	'UNITCOMBAT_HELICOPTER'),
			('PROMOTION_SENTRY', 			'UNITCOMBAT_MELEE'),
			('PROMOTION_SENTRY', 			'UNITCOMBAT_GUN'),
			('PROMOTION_MOBILITY', 			'UNITCOMBAT_MELEE'),
			('PROMOTION_MOBILITY', 			'UNITCOMBAT_GUN'),
			('PROMOTION_FORMATION_2', 		'UNITCOMBAT_MOUNTED'),
			('PROMOTION_AMBUSH_1', 			'UNITCOMBAT_ARMOR'),
			('PROMOTION_AMBUSH_2', 			'UNITCOMBAT_ARMOR');
--==========================================================================================================================	
-- UnitPromotions_PostCombatRandomPromotion
--==========================================================================================================================
DELETE FROM UnitPromotions_PostCombatRandomPromotion WHERE NewPromotion = 'PROMOTION_ENEMY_BLADE';
DELETE FROM UnitPromotions_PostCombatRandomPromotion WHERE NewPromotion = 'PROMOTION_EVIL_SPIRITS';
--==========================================================================================================================
--==========================================================================================================================